services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"

  nginx:
    build: ./frontend   # 🔥 IMPORTANT CHANGE
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend